### ISSUE TITLE
Approaches to structure the problem description

### ISSUE THREAD

**Issue by MaChengxin** [MaChengxin/msc-thesis#1]
There are basically two approaches to structure the problem description:
1. **_from a general problem to Tribler_**: swarm size is an important attribute in P2P file sharing systems, but it is not easy to quickly acquire system-wide knowledge of it... so we use Tribler as a platform to try possible solutions...
2. **_from Tribler to a general problem_**: Tribler doesn't have such a feature, let's add it and say it could also be used by other systems...

Which is better for writing a thesis?

**Comment by qstokkink** [comment]
Definitely 1. Also, you should be able to package this as *subgraph state sampling* or *graph size inference* instead of limiting yourself to *P2P swarm sizes*.

Rationale: experiments should be low level and the actual paper/thesis behind it should be as widely applicable as possible/high level.

**Comment by MaChengxin** [comment]
Thanks for the answer!
